name: Build the nix derivation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix with cached packages
      uses: ibbem/cache-install@b5946e901c509f3478455a3f315e887e254bd36b
      with:
        key: nix-${{ hashFiles('.github/workflows/build.yml', 'default.nix', 'nix/**') }}
        nix_file: nix/github-workflow-dependencies.nix
    - name: Build
      run: nix-build
